USE Profesiask;

CREATE TABLE Companies (
    C_id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Resumes (
    Res_id INT IDENTITY(1,1) PRIMARY KEY,
    Position NVARCHAR(255) NOT NULL,
    Filepath NVARCHAR(255) NOT NULL UNIQUE,
    Language NVARCHAR(50) NOT NULL
);

CREATE TABLE Locations (
    L_id INT IDENTITY(1,1) PRIMARY KEY,
    City NVARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE Vacancies (
	V_id INT IDENTITY(1,1) PRIMARY KEY,
	Position NVARCHAR(128) NOT NULL,
	Link NVARCHAR(850) NOT NULL UNIQUE,
	Salary INT,
	Description NVARCHAR(MAX),
	Company INT NOT NULL,
	Resume INT DEFAULT NULL,
	Location INT NOT NULL,
	haveApplied BIT DEFAULT NULL,
	hasExpired BIT DEFAULT NULL,
	Date DATETIME NOT NULL,
	FOREIGN KEY (Company) REFERENCES Companies(C_id),
	FOREIGN KEY (Resume) REFERENCES Resumes(Res_id),
	FOREIGN KEY (Location) REFERENCES Locations(L_id)
);

CREATE TABLE Knowledges (
    K_id INT IDENTITY(1,1) PRIMARY KEY,
    V_id INT NOT NULL,
    Field NVARCHAR(255),
    Description NVARCHAR(255),
    FOREIGN KEY (V_id) REFERENCES Vacancies(V_id) ON DELETE CASCADE
);

CREATE TABLE Responses (
    Resp_id INT IDENTITY(1,1) PRIMARY KEY,
    isPositive BIT NOT NULL,
    EmailHR NVARCHAR(255) NOT NULL,
    V_id INT NOT NULL,
    FOREIGN KEY (V_id) REFERENCES Vacancies(V_id) ON DELETE CASCADE
);

CREATE TABLE Starred (
    S_id INT IDENTITY(1,1) PRIMARY KEY,
    V_id INT NOT NULL,
    FOREIGN KEY (V_id) REFERENCES Vacancies(V_id) ON DELETE CASCADE
);